# Generated by Django 3.2.9 on 2022-01-18 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
