# Generated by Django 3.2.9 on 2022-01-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_product_producer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='producer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
